# Generated by Django 5.0.10 on 2026-09-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceAnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=20)),
                ('taken_doses', models.IntegerField(default=0)),
                ('missed_doses', models.IntegerField(default=0)),
                ('snoozed_doses', models.IntegerField(default=0)),
                ('adherence_percentage', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to='profiles.patientprofile')),
            ],
        ),
    ]
