# Generated by Django 5.0.10 on 2026-09-07 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('Self', 'Self'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent / Elderly'), ('Sibling', 'Sibling'), ('Other', 'Other')], default='Self', max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='Unspecified', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, default='')),
                ('allergies', models.TextField(blank=True, default='')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
