# Generated by Django 5.0.10 on 2026-09-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Blood Pressure', 'Blood Pressure'), ('Diabetes', 'Diabetes'), ('Thyroid', 'Thyroid'), ('Antibiotics', 'Antibiotics'), ('Vitamins', 'Vitamins'), ('Heart Medications', 'Heart Medications'), ('Other', 'Other')], default='Other', max_length=50)),
                ('dosage', models.CharField(default='1 Tablet', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=30)),
                ('unit', models.CharField(default='tablets', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='profiles.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(default='Morning', max_length=50)),
                ('scheduled_time', models.TimeField()),
                ('dosage_amount', models.CharField(default='1 Tablet', max_length=50)),
                ('frequency', models.CharField(default='1 / day', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='profiles.patientprofile')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medicine')),
            ],
        ),
    ]
