# Generated by Django 5.0.10 on 2026-09-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('parsed_medicine_name', models.CharField(blank=True, default='', max_length=150)),
                ('parsed_dosage', models.CharField(blank=True, default='', max_length=50)),
                ('parsed_quantity', models.IntegerField(default=30)),
                ('parsed_frequency', models.CharField(blank=True, default='', max_length=50)),
                ('confidence', models.FloatField(default=0.9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_logs', to='profiles.patientprofile')),
            ],
        ),
    ]
