import React, { useEffect, useState } from 'react';
import { Camera, CheckCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { getActiveProfile } from '../../features/profile/familyProfileService';
import { saveMedicine, saveSchedule } from '../../features/medications/medicationService';
import { uploadPrescription } from '../../features/ocr/ocrService';

export default function AddMedicinePage() {
  const navigate=useNavigate(); const [profile,setProfile]=useState(null); const [method,setMethod]=useState('manual'); const [ocr,setOcr]=useState(null); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({name:'',dosage:'',stock:30,frequency:'1 / day',time:'08:00',category:'Other',instructions:''});
  useEffect(()=>{getActiveProfile().then(setProfile).catch(e=>setError(e.message));},[]);
  const update=(k,v)=>setForm(f=>({...f,[k]:v}));
  const submit=async(e)=>{e.preventDefault();if(!profile){setError('No patient profile found.');return;}setSaving(true);setError('');try{const med=await saveMedicine({patient_profile:profile.id,name:form.name,dosage:form.dosage,stock_quantity:Number(form.stock),category:form.category,instructions:form.instructions,is_active:true});await saveSchedule({medicine:med.id,patient_profile:profile.id,time_slot:form.time<'12:00'?'Morning':form.time<'17:00'?'Afternoon':'Night',scheduled_time:form.time,dosage_amount:form.dosage||'1 Tablet',frequency:form.frequency,is_active:true});navigate('/patient/medicines');}catch(err){setError(err.message);}finally{setSaving(false);}};
  const scan=async(e)=>{const file=e.target.files?.[0];if(!file)return;setError('');try{const result=await uploadPrescription(file);setOcr(result);setForm(f=>({...f,name:result.medicine_name||f.name,dosage:result.dosage||f.dosage,stock:result.quantity||f.stock,frequency:result.frequency||f.frequency,instructions:result.instructions||f.instructions}));}catch(err){setError(err.message);}};
  return <div style={{maxWidth:720,margin:'0 auto'}}><h2>➕ Add Medicine Schedule</h2><div style={{display:'flex',gap:10,marginBottom:16}}><button onClick={()=>setMethod('manual')} className={method==='manual'?'btn-primary':''}>Manual Entry</button><button onClick={()=>setMethod('ocr')} className={method==='ocr'?'btn-primary':''}>AI OCR Upload</button></div>
  {method==='ocr'&&<div className="glass-card" style={{padding:24,marginBottom:18,textAlign:'center'}}><Camera size={44} color="#DC143C"/><p>Upload a prescription image. The backend will run Tesseract OCR when configured.</p><input type="file" accept="image/*" onChange={scan}/>{ocr&&<div style={{marginTop:15,textAlign:'left',background:'#f0fdf4',padding:14,borderRadius:8}}><CheckCircle size={18} color="#166534"/> Extracted: <strong>{ocr.medicine_name||'Not detected'}</strong>, {ocr.dosage||'dosage not detected'}, {ocr.quantity||'quantity not detected'}, {ocr.frequency||'frequency not detected'} (confidence {Math.round((ocr.confidence||0)*100)}%)</div>}</div>}
  <form onSubmit={submit} className="glass-card" style={{padding:24,display:'flex',flexDirection:'column',gap:14}}><input placeholder="Medicine name" value={form.name} onChange={e=>update('name',e.target.value)} required style={{padding:10}}/><input placeholder="Dosage e.g. 500mg" value={form.dosage} onChange={e=>update('dosage',e.target.value)} required style={{padding:10}}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><input type="number" min="0" placeholder="Stock" value={form.stock} onChange={e=>update('stock',e.target.value)} required style={{padding:10}}/><select value={form.frequency} onChange={e=>update('frequency',e.target.value)} style={{padding:10}}><option>1 / day</option><option>2 / day</option><option>3 / day</option><option>Weekly</option></select></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><input type="time" value={form.time} onChange={e=>update('time',e.target.value)} required style={{padding:10}}/><select value={form.category} onChange={e=>update('category',e.target.value)} style={{padding:10}}><option>Other</option><option>Diabetes</option><option>Blood Pressure</option><option>Thyroid</option><option>Antibiotics</option><option>Vitamins</option><option>Heart Medications</option></select></div><textarea placeholder="Instructions" value={form.instructions} onChange={e=>update('instructions',e.target.value)} style={{padding:10,minHeight:80}}/>{error&&<div style={{color:'#dc2626'}}>{error}</div>}<button className="btn-primary" type="submit" disabled={saving}>{saving?'Saving…':'Save Medicine Schedule'}</button></form></div>;
}
