# Generated by Django 5.0.10 on 2026-09-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(default='1 Tablet', max_length=50)),
                ('action_date', models.DateField()),
                ('action_time', models.CharField(default='08:00 AM', max_length=20)),
                ('status', models.CharField(choices=[('Taken', 'Taken'), ('Missed', 'Missed'), ('Snoozed', 'Snoozed')], default='Taken', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adherence_logs', to='medications.medicine')),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adherence_logs', to='profiles.patientprofile')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adherence_logs', to='medications.medicationschedule')),
            ],
            options={
                'ordering': ['-action_date', '-logged_at'],
            },
        ),
    ]
